# ---------------------------------------------------------------------------
# Git hardening
# ---------------------------------------------------------------------------
secure_git_dir() {
    if [ ! -d "$ECCUBE_ROOT/.git" ]; then
        warn "$ECCUBE_ROOT/.git not found"
        return
    fi
    chown -R root:root "$ECCUBE_ROOT/.git"
    chmod -R go-rwx "$ECCUBE_ROOT/.git"
    info ".git permissions set to root:root go-rwx"
    if ! id "$WEB_USER" >/dev/null 2>&1; then
        warn "Web user '$WEB_USER' not found — verify .git permissions manually"
        return
    fi
    if su -s /bin/sh "$WEB_USER" -c "ls $ECCUBE_ROOT/.git" >/dev/null 2>&1; then
        warn "$WEB_USER can access .git — check permissions"
    else
        info "$WEB_USER .git access denied"
    fi
}

# Write a git hook that restores web user ownership on the working tree, then
# re-secures .git. $1 = hook name, $2 = optional guard line, $3 = header comment.
# The find runs on a single line: a trailing "\" before a newline in the heredoc
# below is consumed as a line continuation, so a multi-line find would collapse anyway.
_write_ownership_hook() {
    local name="$1" guard="$2" comment="$3"
    local hook_path="$ECCUBE_ROOT/.git/hooks/$name"
    if [ ! -d "$ECCUBE_ROOT/.git/hooks" ]; then
        warn "$ECCUBE_ROOT/.git/hooks not found — skipping $name hook"
        return
    fi
    {
        echo "#!/bin/bash"
        echo "# $comment"
        echo "# Generated by eccube-fim install.sh — do not edit manually."
        if [ -n "$guard" ]; then echo "$guard"; fi
        cat <<EOF
WEB_USER="${WEB_USER}"
ECCUBE_ROOT="${ECCUBE_ROOT}"
# only chown files not already owned by web user — avoids IN_ATTRIB flood on rsync watcher
find "\$ECCUBE_ROOT" -not \( -path "\$ECCUBE_ROOT/.git" -prune \) -not -user "\$WEB_USER" -exec chown "\$WEB_USER:\$WEB_USER" {} +
chown -R root:root "\$ECCUBE_ROOT/.git"
chmod -R go-rwx "\$ECCUBE_ROOT/.git"
EOF
    } > "$hook_path"
    chmod 700 "$hook_path"
    chown root:root "$hook_path"
    info "$name hook installed: $hook_path"
}

# post-merge: git pull/merge. post-checkout: git checkout/switch (guard skips file
# checkouts). post-rewrite: git pull --rebase, git commit --amend.
install_git_hooks() {
    _write_ownership_hook post-merge "" \
        "Restore web user ownership on files root wrote during git pull/merge, then re-secure .git."
    _write_ownership_hook post-checkout '[ "$3" = "1" ] || exit 0' \
        "\$3 == 1 means branch checkout; \$3 == 0 means file checkout — skip file checkouts."
    _write_ownership_hook post-rewrite "" \
        "Fires after git pull --rebase and git commit --amend."
}

# known: 53 lines — body is sequential warn output; no extractable logic
_warn_root_ssh() {
    local remote_url
    remote_url=$(git -c "safe.directory=$ECCUBE_ROOT" \
                     -C "$ECCUBE_ROOT" remote get-url origin 2>/dev/null) || return 0

    # HTTP(S) remotes do not need an SSH key
    if echo "$remote_url" | grep -qE '^https?://'; then
        return 0
    fi

    # Root already has a usable private key — no action needed
    if ls /root/.ssh/id_* 2>/dev/null | grep -qv '\.pub$'; then
        return 0
    fi

    local web_home
    web_home=$(getent passwd "$WEB_USER" | cut -d: -f6)

    # Scan candidate dirs: getent home first, then common httpd shared locations
    # because apache's home may be /usr/share/httpd while the key lives elsewhere
    local web_key=""
    for _dir in "${web_home}/.ssh" /usr/share/httpd/.ssh /etc/httpd/.ssh \
                /var/www/.ssh /var/lib/apache/.ssh; do
        for _k in id_ed25519 id_ecdsa id_rsa; do
            [ -f "$_dir/$_k" ] && { web_key="$_dir/$_k"; break 2; }
        done
    done

    warn "Remote is SSH but root has no private key in /root/.ssh/"
    warn "git pull as root will fail with 'Permission denied (publickey)'"
    warn "Choose one of the following options to fix this:"
    echo >&2
    warn "  Option A — reuse the existing deploy key via /root/.ssh/config:"
    warn "    mkdir -p /root/.ssh && chmod 700 /root/.ssh"
    warn "    cat >> /root/.ssh/config <<EOF"
    warn "Host *"
    if [ -n "$web_key" ]; then
        warn "    IdentityFile $web_key"
    else
        warn "    IdentityFile <path-to-${WEB_USER}-deploy-key>"
        warn "    # Locate key: sudo -u $WEB_USER ssh-add -l 2>/dev/null"
        warn "    #             or check ${web_home}/.ssh/ and /etc/httpd/.ssh/"
    fi
    warn "EOF"
    warn "    chmod 600 /root/.ssh/config"
    echo >&2
    warn "  Option B — generate a new key for root and register it:"
    warn "    ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ''"
    warn "    cat /root/.ssh/id_ed25519.pub   # add to GitHub/GitLab deploy keys"
    echo >&2
    warn "  Option C — forward your SSH agent when running git pull:"
    warn "    sudo -E git -c \"safe.directory=$ECCUBE_ROOT\" -C \"$ECCUBE_ROOT\" pull"
}

warn_uncommitted_changes() {
    # match either column: " M" (worktree edit, unstaged) or "M "/"D " (staged)
    if ! git -c "safe.directory=$ECCUBE_ROOT" -C "$ECCUBE_ROOT" \
            status --porcelain 2>/dev/null | grep -qE '^.?[MD]'; then
        return
    fi
    warn "Uncommitted changes detected in $ECCUBE_ROOT"
    git -c "safe.directory=$ECCUBE_ROOT" -C "$ECCUBE_ROOT" status --short
}

