# lib/installer/wizard_notify.sh
# Notify wizard — shared by install.sh and install-malware.sh.
# Depends on: CONFIG_DIR, NONINTERACTIVE, RECONFIGURE (set in header.sh)

_secure_file() { chmod 600 "$1"; chown root:root "$1"; }

# prompt VAR_NAME "Label" "default" [secret]
# Non-interactive: reads from env var $VAR_NAME; aborts if required and unset.
prompt() {
    local var="$1" label="$2" default="$3" secret="${4:-}"
    if [ "$NONINTERACTIVE" -eq 1 ]; then
        local env_val
        env_val="${!var:-}"
        if [ -z "$env_val" ] && [ -z "$default" ]; then
            error "--non-interactive: $var is required but not set"; exit 1
        fi
        printf -v "$var" '%s' "${env_val:-$default}"
        return
    fi
    local display_label="$label"
    [ -n "$default" ] && display_label="$label [$default]"
    local input=""
    if [ -n "$secret" ]; then
        read -rsp "${display_label}: " input </dev/tty; echo
    else
        read -rp "${display_label}: " input </dev/tty
    fi
    printf -v "$var" '%s' "${input:-$default}"
}

validate_email() {
    # full RFC 5321 parsing would reject valid addresses; structural check suffices
    [[ "$1" =~ ^[^@]+@[^@]+$ ]] || { error "Invalid email address: $1"; exit 1; }
}

prompt_email_enabled() {
    echo
    info "=== Email alerts ==="
    EMAIL_ENABLED=true
    [ "$NONINTERACTIVE" -eq 1 ] && return 0
    read -rp "Enable email notifications? [Y/n]: " yn </dev/tty
    if [ "${yn,,}" = "n" ]; then
        EMAIL_ENABLED=false
    fi
}

prompt_email() {
    echo
    info "=== Email credentials ==="
    prompt SMTP_HOST      "SMTP host"                    ""
    prompt SMTP_PORT      "SMTP port"                    "587"
    prompt SMTP_USER      "SMTP user"                    ""
    prompt SMTP_PASSWORD  "SMTP password"                "" secret
    prompt EMAIL_FROM     "From address"                 "$SMTP_USER"
    prompt EMAIL_RCPT_RAW "Recipients (comma-separated)" ""
    [ -n "$EMAIL_RCPT_RAW" ] || { error "At least one recipient is required"; exit 1; }
    validate_email "$EMAIL_FROM"
    IFS=',' read -ra _rcpts <<< "$EMAIL_RCPT_RAW"
    for _r in "${_rcpts[@]}"; do
        _r="${_r// /}"
        [ -n "$_r" ] && validate_email "$_r"
    done
}

prompt_slack() {
    echo
    info "=== Slack alerts (optional) ==="
    SLACK_ENABLED=false
    SLACK_WEBHOOKS=()
    [ "$NONINTERACTIVE" -eq 1 ] && return 0
    read -rp "Enable Slack notifications? [y/N]: " yn </dev/tty
    if [ "${yn,,}" != "y" ]; then
        return 0
    fi
    SLACK_ENABLED=true
    local i=1
    while true; do
        local wh=""
        read -rp "Slack webhook URL $i (empty to stop): " wh </dev/tty
        [ -z "$wh" ] && break
        local wh_file="$CONFIG_DIR/slack-${i}.webhook"
        printf '%s' "$wh" > "$wh_file"
        _secure_file "$wh_file"
        SLACK_WEBHOOKS+=("$wh_file")
        i=$((i + 1))
    done
}

write_notify_yaml() {
    local slack_files_yaml="" wh_file
    for wh_file in ${SLACK_WEBHOOKS[@]+"${SLACK_WEBHOOKS[@]}"}; do
        slack_files_yaml="${slack_files_yaml}    - ${wh_file}"$'\n'
    done
    if [ "$EMAIL_ENABLED" = "false" ]; then
        cat > "$CONFIG_DIR/notify.yaml" <<EOF
# Generated by %%SCRIPT_NAME%% ${VERSION}
email:
  enabled: false
slack:
  enabled: $SLACK_ENABLED
  webhook_url_files:
${slack_files_yaml}
EOF
        _secure_file "$CONFIG_DIR/notify.yaml"
        info "Written $CONFIG_DIR/notify.yaml (email disabled)"
        return
    fi
    local rcpt_yaml="" r
    IFS=',' read -ra rcpts <<< "$EMAIL_RCPT_RAW"
    for r in "${rcpts[@]}"; do
        r="${r// /}"
        rcpt_yaml="${rcpt_yaml}    - ${r}"$'\n'
    done
    cat > "$CONFIG_DIR/notify.yaml" <<EOF
# Generated by %%SCRIPT_NAME%% ${VERSION}
email:
  smtp_host: $SMTP_HOST
  smtp_port: $SMTP_PORT
  smtp_user: $SMTP_USER
  smtp_password_file: $CONFIG_DIR/smtp.password
  from: $EMAIL_FROM
  recipients:
${rcpt_yaml}
slack:
  enabled: $SLACK_ENABLED
  webhook_url_files:
${slack_files_yaml}
EOF
    _secure_file "$CONFIG_DIR/notify.yaml"
    info "Written $CONFIG_DIR/notify.yaml"
}

write_smtp_password() {
    printf '%s' "$SMTP_PASSWORD" > "$CONFIG_DIR/smtp.password"
    _secure_file "$CONFIG_DIR/smtp.password"
    info "Written $CONFIG_DIR/smtp.password"
}

wizard_notify() {
    local notify_f="$CONFIG_DIR/notify.yaml"
    # Skip when notify.yaml exists and operator did not pass --reconfigure
    if [ -f "$notify_f" ] && [ "$RECONFIGURE" -eq 0 ]; then
        info "Existing notify.yaml found — skipping notify wizard (use --reconfigure to change)"
        return
    fi
    # curl|bash: stdin is the pipe; each read uses </dev/tty directly
    if [ ! -t 0 ]; then
        [ -c /dev/tty ] || {
            error "No terminal — use --non-interactive or run: sudo bash %%SCRIPT_NAME%%"
            exit 1
        }
    fi
    prompt_email_enabled
    if [ "$EMAIL_ENABLED" = "true" ]; then
        prompt_email
    fi
    prompt_slack
    write_notify_yaml
    if [ "$EMAIL_ENABLED" = "true" ]; then
        write_smtp_password
    fi
}
