# ---------------------------------------------------------------------------
# Interactive wizard — FIM-specific steps only
# ---------------------------------------------------------------------------
# Notify functions (_secure_file, prompt, validate_email, prompt_email_enabled,
# prompt_email, prompt_slack, write_notify_yaml, write_smtp_password, wizard_notify)
# live in wizard_notify.sh — included before this file in both build targets.

prompt_infra() {
    echo
    info "=== Infrastructure ==="
    prompt ECCUBE_ROOT    "EC-CUBE root path"        "/var/www/html"
    prompt CHECK_INTERVAL "Check interval (minutes)" "15"
    [ -d "$ECCUBE_ROOT" ] || warn "$ECCUBE_ROOT not found — create it before starting the service"
    echo "$CHECK_INTERVAL" | grep -qE '^[1-9][0-9]*$' \
        || { error "Interval must be a positive integer"; exit 1; }
}

write_daemon_yaml() {
    cat > "$CONFIG_DIR/daemon.yaml" <<EOF
# Generated by eccube-fim install.sh ${VERSION}
root_path: $ECCUBE_ROOT
state_db: $CONFIG_DIR/state.db
heartbeat:
  enabled: true
  file: $RUN_DIR/heartbeat
EOF
    _secure_file "$CONFIG_DIR/daemon.yaml"
    info "Written $CONFIG_DIR/daemon.yaml"
}

write_targets_yaml() {
    local f="$CONFIG_DIR/targets.yaml"
    if [ -f "$f" ] && [ "$RECONFIGURE" -eq 0 ]; then
        info "$f exists — skipping (preserves operator customisations)"
        return
    fi
    cp "$SRC_DIR/config/targets.yaml.sample" "$f"
    _secure_file "$f"
    info "Written $f"
}

_read_interval_from_timer() {
    local calendar
    calendar=$(systemctl cat eccube-fim-check.timer 2>/dev/null | awk -F= '/^OnCalendar=/{print $2}')
    CHECK_INTERVAL="${calendar##*:0/}"
    CHECK_INTERVAL="${CHECK_INTERVAL:-15}"
}

wizard() {
    local daemon_f="$CONFIG_DIR/daemon.yaml"
    local notify_f="$CONFIG_DIR/notify.yaml"
    # Skip wizard whenever configs exist — interactive or not — unless --reconfigure
    if [ -f "$daemon_f" ] && [ -f "$notify_f" ] && [ "$RECONFIGURE" -eq 0 ]; then
        info "Existing config found — skipping wizard (use --reconfigure to change settings)"
        ECCUBE_ROOT=$(awk '/^root_path:/{print $2}' "$daemon_f")
        ECCUBE_ROOT="${ECCUBE_ROOT:-/var/www/html}"
        _read_interval_from_timer
        return
    fi
    prompt_infra
    wizard_notify      # tty guard + email/Slack prompts + writes notify.yaml
    write_daemon_yaml
    write_targets_yaml
}
