# ---------------------------------------------------------------------------
# Interactive wizard
# ---------------------------------------------------------------------------
# known: 201 lines — bash has no module system; all write_* functions belong here

_secure_file() { chmod 600 "$1"; chown root:root "$1"; }

# prompt VAR_NAME "Label" "default" [secret]
# Non-interactive: reads from env var $VAR_NAME; aborts if required and unset.
prompt() {
    local var="$1" label="$2" default="$3" secret="${4:-}"
    if [ "$NONINTERACTIVE" -eq 1 ]; then
        local env_val
        env_val="${!var:-}"
        if [ -z "$env_val" ] && [ -z "$default" ]; then
            error "--non-interactive: $var is required but not set"; exit 1
        fi
        printf -v "$var" '%s' "${env_val:-$default}"
        return
    fi
    local display_label="$label"
    [ -n "$default" ] && display_label="$label [$default]"
    local input=""
    if [ -n "$secret" ]; then
        read -rsp "${display_label}: " input </dev/tty; echo
    else
        read -rp "${display_label}: " input </dev/tty
    fi
    printf -v "$var" '%s' "${input:-$default}"
}

prompt_infra() {
    echo
    info "=== Infrastructure ==="
    prompt ECCUBE_ROOT    "EC-CUBE root path"        "/var/www/html"
    prompt CHECK_INTERVAL "Check interval (minutes)" "15"
    [ -d "$ECCUBE_ROOT" ] || warn "$ECCUBE_ROOT not found — create it before starting the service"
    echo "$CHECK_INTERVAL" | grep -qE '^[1-9][0-9]*$' \
        || { error "Interval must be a positive integer"; exit 1; }
}

prompt_email_enabled() {
    echo
    info "=== Email alerts ==="
    EMAIL_ENABLED=true
    [ "$NONINTERACTIVE" -eq 1 ] && return 0
    read -rp "Enable email notifications? [Y/n]: " yn </dev/tty
    if [ "${yn,,}" = "n" ]; then
        EMAIL_ENABLED=false
    fi
}

prompt_email() {
    echo
    info "=== Email credentials ==="
    prompt SMTP_HOST      "SMTP host"                    ""
    prompt SMTP_PORT      "SMTP port"                    "587"
    prompt SMTP_USER      "SMTP user"                    ""
    prompt SMTP_PASSWORD  "SMTP password"                "" secret
    prompt EMAIL_FROM     "From address"                 "$SMTP_USER"
    prompt EMAIL_RCPT_RAW "Recipients (comma-separated)" ""
    [ -n "$EMAIL_RCPT_RAW" ] || { error "At least one recipient is required"; exit 1; }
}

prompt_slack() {
    echo
    info "=== Slack alerts (optional) ==="
    SLACK_ENABLED=false
    SLACK_WEBHOOKS=()
    [ "$NONINTERACTIVE" -eq 1 ] && return 0
    read -rp "Enable Slack notifications? [y/N]: " yn </dev/tty
    if [ "${yn,,}" != "y" ]; then
        return 0
    fi
    SLACK_ENABLED=true
    local i=1
    while true; do
        local wh=""
        read -rp "Slack webhook URL $i (empty to stop): " wh </dev/tty
        [ -z "$wh" ] && break
        local wh_file="$CONFIG_DIR/slack-${i}.webhook"
        printf '%s' "$wh" > "$wh_file"
        _secure_file "$wh_file"
        SLACK_WEBHOOKS+=("$wh_file")
        i=$((i + 1))
    done
}

write_daemon_yaml() {
    cat > "$CONFIG_DIR/daemon.yaml" <<EOF
# Generated by eccube-fim install.sh ${VERSION}
root_path: $ECCUBE_ROOT
state_db: $CONFIG_DIR/state.db
heartbeat:
  enabled: true
  file: $RUN_DIR/heartbeat
EOF
    _secure_file "$CONFIG_DIR/daemon.yaml"
    info "Written $CONFIG_DIR/daemon.yaml"
}

write_targets_yaml() {
    local f="$CONFIG_DIR/targets.yaml"
    if [ -f "$f" ] && [ "$RECONFIGURE" -eq 0 ]; then
        info "$f exists — skipping (preserves operator customisations)"
        return
    fi
    cp "$SRC_DIR/config/targets.yaml.sample" "$f"
    _secure_file "$f"
    info "Written $f"
}

write_notify_yaml() {
    local slack_files_yaml="" wh_file
    for wh_file in ${SLACK_WEBHOOKS[@]+"${SLACK_WEBHOOKS[@]}"}; do
        slack_files_yaml="${slack_files_yaml}    - ${wh_file}"$'\n'
    done
    if [ "$EMAIL_ENABLED" = "false" ]; then
        cat > "$CONFIG_DIR/notify.yaml" <<EOF
# Generated by eccube-fim install.sh ${VERSION}
email:
  enabled: false
slack:
  enabled: $SLACK_ENABLED
  webhook_url_files:
${slack_files_yaml}
EOF
        _secure_file "$CONFIG_DIR/notify.yaml"
        info "Written $CONFIG_DIR/notify.yaml (email disabled)"
        return
    fi
    local rcpt_yaml="" r
    IFS=',' read -ra rcpts <<< "$EMAIL_RCPT_RAW"
    for r in "${rcpts[@]}"; do
        r="${r// /}"
        rcpt_yaml="${rcpt_yaml}    - ${r}"$'\n'
    done
    cat > "$CONFIG_DIR/notify.yaml" <<EOF
# Generated by eccube-fim install.sh ${VERSION}
email:
  smtp_host: $SMTP_HOST
  smtp_port: $SMTP_PORT
  smtp_user: $SMTP_USER
  smtp_password_file: $CONFIG_DIR/smtp.password
  from: $EMAIL_FROM
  recipients:
${rcpt_yaml}
slack:
  enabled: $SLACK_ENABLED
  webhook_url_files:
${slack_files_yaml}
EOF
    _secure_file "$CONFIG_DIR/notify.yaml"
    info "Written $CONFIG_DIR/notify.yaml"
}

write_smtp_password() {
    printf '%s' "$SMTP_PASSWORD" > "$CONFIG_DIR/smtp.password"
    _secure_file "$CONFIG_DIR/smtp.password"
    info "Written $CONFIG_DIR/smtp.password"
}

_read_interval_from_timer() {
    local calendar
    calendar=$(systemctl cat eccube-fim-check.timer 2>/dev/null | awk -F= '/^OnCalendar=/{print $2}')
    CHECK_INTERVAL="${calendar##*:0/}"
    CHECK_INTERVAL="${CHECK_INTERVAL:-15}"
}

wizard() {
    local daemon_f="$CONFIG_DIR/daemon.yaml"
    local notify_f="$CONFIG_DIR/notify.yaml"
    # Skip wizard whenever configs exist — interactive or not — unless --reconfigure
    if [ -f "$daemon_f" ] && [ -f "$notify_f" ] && [ "$RECONFIGURE" -eq 0 ]; then
        info "Existing config found — skipping wizard (use --reconfigure to change settings)"
        ECCUBE_ROOT=$(awk '/^root_path:/{print $2}' "$daemon_f")
        ECCUBE_ROOT="${ECCUBE_ROOT:-/var/www/html}"
        _read_interval_from_timer
        return
    fi
    # curl|bash: stdin is the pipe carrying the script, not the terminal.
    # Each read in prompt() and prompt_slack() uses </dev/tty directly so
    # bash's stdin never changes — no exec redirect needed here.
    if [ ! -t 0 ]; then
        [ -c /dev/tty ] || { error "No terminal available — use --non-interactive or run directly: sudo bash install.sh"; exit 1; }
    fi
    prompt_infra
    prompt_email_enabled
    if [ "$EMAIL_ENABLED" = "true" ]; then
        prompt_email
    fi
    prompt_slack
    write_daemon_yaml
    write_targets_yaml
    write_notify_yaml
    if [ "$EMAIL_ENABLED" = "true" ]; then
        write_smtp_password
    fi
}

