#!/bin/bash
# install.sh — EC-CUBE FIM install / update / reconfigure
# DO NOT EDIT — generated by build.sh from lib/installer/*.sh
# Run as root on a systemd Linux host.
set -euo pipefail

SBIN_DIR=/usr/local/sbin
LIB_DIR=/usr/local/lib/eccube-fim
CONFIG_DIR=/etc/eccube-fim
LOG_DIR=/var/log/eccube-fim
RUN_DIR=/run/eccube-fim
STATUS_DIR=/var/lib/eccube-fim

REPO_SLUG="arstokyo/eccube-fim"
REPO="https://github.com/${REPO_SLUG}"
RELEASES_API="https://api.github.com/repos/${REPO_SLUG}/releases/latest"

NONINTERACTIVE=0
RECONFIGURE=0
UPDATE=0
FORCE=0
VERSION=""          # set by _fetch_release_info()
PYTHON_REQUIRES=""  # set by _fetch_release_info()
SRC_DIR=""

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
info()  { echo -e "\033[32m[INFO]\033[0m  $*"; }
warn()  { echo -e "\033[33m[WARN]\033[0m  $*"; }
error() { echo -e "\033[31m[ERROR]\033[0m $*" >&2; }

# ---------------------------------------------------------------------------
# Arg parsing
# ---------------------------------------------------------------------------
parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --non-interactive) NONINTERACTIVE=1 ;;
            --reconfigure)     RECONFIGURE=1 ;;
            --update)          UPDATE=1 ;;
            --force)           FORCE=1 ;;
            *) error "Unknown argument: $1"; exit 1 ;;
        esac
        shift
    done
    if [ "$UPDATE" -eq 1 ] && [ "$RECONFIGURE" -eq 1 ]; then
        error "--update and --reconfigure are mutually exclusive"; exit 1
    fi
    # --force is a retry path after a failed --update; meaningless without --update
    if [ "$FORCE" -eq 1 ] && [ "$UPDATE" -eq 0 ]; then
        error "--force requires --update (use: sudo bash install.sh --update --force)"; exit 1
    fi
}

# ---------------------------------------------------------------------------
# OS detection
# ---------------------------------------------------------------------------
require_root() {
    [ "$(id -u)" -eq 0 ] || { error "Must be run as root"; exit 1; }
}

detect_os() {
    [ -f /etc/os-release ] || { echo "unknown"; return; }
    # shellcheck source=/dev/null
    . /etc/os-release
    echo "${ID:-unknown}"
}

configure_os() {
    OS_ID=$(detect_os)
    case "$OS_ID" in
        ol|rhel|centos|rocky|almalinux|fedora)
            PKG_MGR="dnf"; PYYAML_PKG="python3-pyyaml"; WEB_USER="apache" ;;
        ubuntu|debian|linuxmint|pop)
            PKG_MGR="apt-get"; PYYAML_PKG="python3-yaml"; WEB_USER="www-data" ;;
        opensuse*|sles|sled)
            PKG_MGR="zypper"; PYYAML_PKG="python3-PyYAML"; WEB_USER="wwwrun" ;;
        arch|manjaro|endeavouros)
            PKG_MGR="pacman"; PYYAML_PKG="python-yaml"; WEB_USER="http" ;;
        alpine)
            error "Alpine Linux is not supported (OpenRC — systemd required)"; exit 1 ;;
        *)
            error "Unsupported OS: $OS_ID"; exit 1 ;;
    esac
}

# ---------------------------------------------------------------------------
# Source fetch — latest GitHub Release only; errors on network failure
# ---------------------------------------------------------------------------
_fetch_release_info() {
    local response
    response=$(curl -fsSL "$RELEASES_API" 2>/dev/null) || true
    VERSION=$(echo "$response" | grep '"tag_name"' | cut -d'"' -f4)
    if [ -z "$VERSION" ]; then
        error "Could not resolve latest release."
        error "Check your network or visit: https://github.com/${REPO_SLUG}/releases"
        exit 1
    fi
    PYTHON_REQUIRES=$(echo "$response" | python3 -c "
import json, sys, re
try:
    data = json.load(sys.stdin)
    body = data.get('body', '')
    m = re.search(r'python_requires:\s*\"(.*?)\"', body)
    print(m.group(1) if m else '')
except Exception:
    print('')
" 2>/dev/null || echo "")
}

_check_python_requires() {
    local requires="$1"
    [ -z "$requires" ] && return
    python3 -c "
import sys, re
requires = '${requires}'
min_ver = tuple(int(x) for x in re.sub(r'^[>=]+', '', requires).split('.'))
actual  = sys.version_info[:len(min_ver)]
if actual < min_ver:
    needed  = '.'.join(str(x) for x in min_ver)
    running = f'{sys.version_info.major}.{sys.version_info.minor}'
    print(f'ERROR: This release requires Python {needed}+ (found Python {running}).',
          file=sys.stderr)
    print('You are already on the latest version compatible with your Python.',
          file=sys.stderr)
    sys.exit(1)
" || exit 1
}

_download_release_asset() {
    local asset_name="$1"
    local dest_dir="$2"
    local url="${REPO}/releases/download/${VERSION}/${asset_name}"
    info "Downloading ${asset_name}..."
    if ! curl -fsSL "$url" | tar xz --strip-components=1 -C "$dest_dir"; then
        error "Download failed: ${asset_name}"
        error "Check the release assets: ${REPO}/releases/tag/${VERSION}"
        exit 1
    fi
}

_prepare_release_source_dir() {
    SRC_DIR="$(mktemp -d)"
    # shellcheck disable=SC2064
    # double-quoted: bake in SRC_DIR now so EXIT cleanup still has the path
    trap "rm -rf '$SRC_DIR'" EXIT
}

fetch_source() {
    local script_dir
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-}")" 2>/dev/null && pwd || echo "")"
    if [ -d "${script_dir}/fim" ] && [ -d "${script_dir}/common" ]; then
        SRC_DIR="$script_dir"
        VERSION="local"
        info "Using local source: $SRC_DIR"
        return
    fi
    _fetch_release_info
    _check_python_requires "$PYTHON_REQUIRES"
    _prepare_release_source_dir
    _download_release_asset "eccube-common-${VERSION}.tar.gz" "$SRC_DIR"
    _download_release_asset "eccube-fim-${VERSION}.tar.gz" "$SRC_DIR"
    info "Source ready: eccube-fim ${VERSION}"
}

# ---------------------------------------------------------------------------
# Package + directory setup
# ---------------------------------------------------------------------------
_check_sshd_health() {
    # sshd -t validates both config and OpenSSL ABI linkage
    if ! sshd -t >/dev/null 2>&1; then
        error "sshd validation failed after package install — do NOT disconnect this session"
        error "Recovery: dnf update openssh openssh-server -y && systemctl restart sshd"
        error "Verify  : sshd -t && ss -tlnp | grep :22"
        exit 1
    fi
}

install_packages() {
    info "Installing packages with $PKG_MGR"
    case "$PKG_MGR" in
        dnf)
            warn "Keep a second SSH session open — package operations may update OpenSSL"
            dnf install -y --setopt=install_weak_deps=False python3 "$PYYAML_PKG" git
            _check_sshd_health
            ;;
        apt-get) apt-get update -qq
                 apt-get install -y --no-install-recommends python3 "$PYYAML_PKG" git ;;
        zypper)  zypper install -y python3 "$PYYAML_PKG" git ;;
        pacman)  pacman -Sy --noconfirm python "$PYYAML_PKG" git ;;
    esac
}

create_directories() {
    info "Creating directories"
    for dir in "$CONFIG_DIR" "$LOG_DIR" "$RUN_DIR"; do
        mkdir -p "$dir"
        chmod 700 "$dir"
        chown root:root "$dir"
    done
    mkdir -p "$LIB_DIR"
    chmod 755 "$LIB_DIR"
    chown root:root "$LIB_DIR"
    # 755 world-readable: web process (apache/www-data) traverses dir to read status.json
    mkdir -p "$STATUS_DIR"
    chmod 755 "$STATUS_DIR"
    chown root:root "$STATUS_DIR"
}

setup_tmpfiles() {
    # /run is tmpfs on systemd distros; recreate runtime dir after reboot
    cat > /etc/tmpfiles.d/eccube-fim.conf <<EOF
d $RUN_DIR 0700 root root -
EOF
    systemd-tmpfiles --create /etc/tmpfiles.d/eccube-fim.conf
    info "Configured tmpfiles.d for $RUN_DIR"
}

# ---------------------------------------------------------------------------
# Companion version guard helpers
# ---------------------------------------------------------------------------
installed_version() {
    local stamp="${CONFIG_DIR}/.version"
    if [ ! -f "$stamp" ]; then
        # No stamp means companion was installed before plan-082 introduced the stamp.
        # Read __version__ from the companion Python module as a fallback so the
        # version guard can still compare correctly.
        local ver
        ver=$(python3 -c "
import sys
sys.path.insert(0, '${LIB_DIR}')
try:
    from common.version import __version__; print(__version__)
except Exception:
    print('unknown')
" 2>/dev/null)
        echo "$ver"
        return
    fi
    tr -d '[:space:]' < "$stamp"
}

target_version() {
    echo "${VERSION#v}"
}

fim_installed() {
    [ -d "${LIB_DIR}/fim" ] || [ -x "${SBIN_DIR}/eccube-fim" ]
}

malware_installed() {
    [ -d "${LIB_DIR}/malware" ] || [ -x "${SBIN_DIR}/eccube-malware" ]
}

# Generic version guard — called by guard_existing_fim_version(), guard_existing_malware_version()
guard_existing_version() {
    local module="$1" bin_name="$2"
    [ "$VERSION" = "local" ] && return 0
    case "$module" in
        fim)     fim_installed     || return 0 ;;
        malware) malware_installed || return 0 ;;
        *)       error "guard_existing_version: unknown module '$module'"; exit 1 ;;
    esac
    local installed target
    installed="$(installed_version)"
    target="$(target_version)"
    [ "$installed" = "$target" ] && return 0
    error "Existing $bin_name installation detected at version ${installed}."
    error "This installer will install eccube-common ${target}; mixed versions are unsafe."
    error "Run first: sudo $bin_name upgrade"
    error "Then rerun this installer."
    exit 1
}

guard_existing_malware_version() {
    guard_existing_version "malware" "eccube-malware"
}

guard_existing_fim_version() {
    guard_existing_version "fim" "eccube-fim"
}

# ---------------------------------------------------------------------------
# Library + CLI install
# ---------------------------------------------------------------------------
# Generic library installer — called by install_common_library(), install_fim_library(), install_malware_library()
install_library_module() {
    local module="$1"
    [ -n "$module" ] || { error "install_library_module: module name required"; exit 1; }
    info "Installing $module Python library"
    mkdir -p "$LIB_DIR"
    rm -rf "$LIB_DIR/$module"
    cp -r "$SRC_DIR/$module" "$LIB_DIR/$module"
    find "$LIB_DIR/$module" -type d -exec chmod 755 {} \;
    find "$LIB_DIR/$module" -type f -exec chmod 644 {} \;
    chown -R root:root "$LIB_DIR/$module"
}

install_common_library() {
    install_library_module "common"
}

install_fim_library() {
    install_library_module "fim"
}

install_version_stamp() {
    info "Writing version stamp (${VERSION#v})"
    printf '%s\n' "${VERSION#v}" > "$CONFIG_DIR/.version"
    chmod 644 "$CONFIG_DIR/.version"
    chown root:root "$CONFIG_DIR/.version"
}

install_cli() {
    info "Installing unified CLI"
    install -m 755 -o root -g root "$SRC_DIR/bin/eccube-fim" "$SBIN_DIR/eccube-fim"
}

install_logrotate() {
    info "Installing logrotate config"
    install -m 644 -o root -g root "$SRC_DIR/eccube-fim.logrotate" /etc/logrotate.d/eccube-fim
}

# lib/installer/wizard_notify.sh
# Notify wizard — shared by install.sh and install-malware.sh.
# Depends on: CONFIG_DIR, NONINTERACTIVE, RECONFIGURE (set in header.sh)

_secure_file() { chmod 600 "$1"; chown root:root "$1"; }

# prompt VAR_NAME "Label" "default" [secret]
# Non-interactive: reads from env var $VAR_NAME; aborts if required and unset.
prompt() {
    local var="$1" label="$2" default="$3" secret="${4:-}"
    if [ "$NONINTERACTIVE" -eq 1 ]; then
        local env_val
        env_val="${!var:-}"
        if [ -z "$env_val" ] && [ -z "$default" ]; then
            error "--non-interactive: $var is required but not set"; exit 1
        fi
        printf -v "$var" '%s' "${env_val:-$default}"
        return
    fi
    local display_label="$label"
    [ -n "$default" ] && display_label="$label [$default]"
    local input=""
    if [ -n "$secret" ]; then
        read -rsp "${display_label}: " input </dev/tty; echo
    else
        read -rp "${display_label}: " input </dev/tty
    fi
    printf -v "$var" '%s' "${input:-$default}"
}

validate_email() {
    # full RFC 5321 parsing would reject valid addresses; structural check suffices
    [[ "$1" =~ ^[^@]+@[^@]+$ ]] || { error "Invalid email address: $1"; exit 1; }
}

prompt_email_enabled() {
    echo
    info "=== Email alerts ==="
    EMAIL_ENABLED=true
    [ "$NONINTERACTIVE" -eq 1 ] && return 0
    read -rp "Enable email notifications? [Y/n]: " yn </dev/tty
    if [ "${yn,,}" = "n" ]; then
        EMAIL_ENABLED=false
    fi
}

prompt_email() {
    echo
    info "=== Email credentials ==="
    prompt SMTP_HOST      "SMTP host"                    ""
    prompt SMTP_PORT      "SMTP port"                    "587"
    prompt SMTP_USER      "SMTP user"                    ""
    prompt SMTP_PASSWORD  "SMTP password"                "" secret
    prompt EMAIL_FROM     "From address"                 "$SMTP_USER"
    prompt EMAIL_RCPT_RAW "Recipients (comma-separated)" ""
    [ -n "$EMAIL_RCPT_RAW" ] || { error "At least one recipient is required"; exit 1; }
    validate_email "$EMAIL_FROM"
    IFS=',' read -ra _rcpts <<< "$EMAIL_RCPT_RAW"
    for _r in "${_rcpts[@]}"; do
        _r="${_r// /}"
        [ -n "$_r" ] && validate_email "$_r"
    done
}

prompt_slack() {
    echo
    info "=== Slack alerts (optional) ==="
    SLACK_ENABLED=false
    SLACK_WEBHOOKS=()
    [ "$NONINTERACTIVE" -eq 1 ] && return 0
    read -rp "Enable Slack notifications? [y/N]: " yn </dev/tty
    if [ "${yn,,}" != "y" ]; then
        return 0
    fi
    SLACK_ENABLED=true
    local i=1
    while true; do
        local wh=""
        read -rp "Slack webhook URL $i (empty to stop): " wh </dev/tty
        [ -z "$wh" ] && break
        local wh_file="$CONFIG_DIR/slack-${i}.webhook"
        printf '%s' "$wh" > "$wh_file"
        _secure_file "$wh_file"
        SLACK_WEBHOOKS+=("$wh_file")
        i=$((i + 1))
    done
}

write_notify_yaml() {
    local slack_files_yaml="" wh_file
    for wh_file in ${SLACK_WEBHOOKS[@]+"${SLACK_WEBHOOKS[@]}"}; do
        slack_files_yaml="${slack_files_yaml}    - ${wh_file}"$'\n'
    done
    if [ "$EMAIL_ENABLED" = "false" ]; then
        cat > "$CONFIG_DIR/notify.yaml" <<EOF
# Generated by install.sh ${VERSION}
email:
  enabled: false
slack:
  enabled: $SLACK_ENABLED
  webhook_url_files:
${slack_files_yaml}
EOF
        _secure_file "$CONFIG_DIR/notify.yaml"
        info "Written $CONFIG_DIR/notify.yaml (email disabled)"
        return
    fi
    local rcpt_yaml="" r
    IFS=',' read -ra rcpts <<< "$EMAIL_RCPT_RAW"
    for r in "${rcpts[@]}"; do
        r="${r// /}"
        rcpt_yaml="${rcpt_yaml}    - ${r}"$'\n'
    done
    cat > "$CONFIG_DIR/notify.yaml" <<EOF
# Generated by install.sh ${VERSION}
email:
  smtp_host: $SMTP_HOST
  smtp_port: $SMTP_PORT
  smtp_user: $SMTP_USER
  smtp_password_file: $CONFIG_DIR/smtp.password
  from: $EMAIL_FROM
  recipients:
${rcpt_yaml}
slack:
  enabled: $SLACK_ENABLED
  webhook_url_files:
${slack_files_yaml}
EOF
    _secure_file "$CONFIG_DIR/notify.yaml"
    info "Written $CONFIG_DIR/notify.yaml"
}

write_smtp_password() {
    printf '%s' "$SMTP_PASSWORD" > "$CONFIG_DIR/smtp.password"
    _secure_file "$CONFIG_DIR/smtp.password"
    info "Written $CONFIG_DIR/smtp.password"
}

wizard_notify() {
    local notify_f="$CONFIG_DIR/notify.yaml"
    # Skip when notify.yaml exists and operator did not pass --reconfigure
    if [ -f "$notify_f" ] && [ "$RECONFIGURE" -eq 0 ]; then
        info "Existing notify.yaml found — skipping notify wizard (use --reconfigure to change)"
        return
    fi
    # curl|bash: stdin is the pipe; each read uses </dev/tty directly
    if [ ! -t 0 ]; then
        [ -c /dev/tty ] || {
            error "No terminal — use --non-interactive or run: sudo bash install.sh"
            exit 1
        }
    fi
    prompt_email_enabled
    if [ "$EMAIL_ENABLED" = "true" ]; then
        prompt_email
    fi
    prompt_slack
    write_notify_yaml
    if [ "$EMAIL_ENABLED" = "true" ]; then
        write_smtp_password
    fi
}
# ---------------------------------------------------------------------------
# Interactive wizard — FIM-specific steps only
# ---------------------------------------------------------------------------
# Notify functions (_secure_file, prompt, validate_email, prompt_email_enabled,
# prompt_email, prompt_slack, write_notify_yaml, write_smtp_password, wizard_notify)
# live in wizard_notify.sh — included before this file in both build targets.

prompt_infra() {
    echo
    info "=== Infrastructure ==="
    prompt ECCUBE_ROOT    "EC-CUBE root path"        "/var/www/html"
    prompt CHECK_INTERVAL "Check interval (minutes)" "15"
    [ -d "$ECCUBE_ROOT" ] || warn "$ECCUBE_ROOT not found — create it before starting the service"
    echo "$CHECK_INTERVAL" | grep -qE '^[1-9][0-9]*$' \
        || { error "Interval must be a positive integer"; exit 1; }
}

write_daemon_yaml() {
    cat > "$CONFIG_DIR/daemon.yaml" <<EOF
# Generated by eccube-fim install.sh ${VERSION}
root_path: $ECCUBE_ROOT
state_db: $CONFIG_DIR/state.db
heartbeat:
  enabled: true
  file: $RUN_DIR/heartbeat
EOF
    _secure_file "$CONFIG_DIR/daemon.yaml"
    info "Written $CONFIG_DIR/daemon.yaml"
}

write_targets_yaml() {
    local f="$CONFIG_DIR/targets.yaml"
    if [ -f "$f" ] && [ "$RECONFIGURE" -eq 0 ]; then
        info "$f exists — skipping (preserves operator customisations)"
        return
    fi
    cp "$SRC_DIR/config/targets.yaml.sample" "$f"
    _secure_file "$f"
    info "Written $f"
}

_read_interval_from_timer() {
    local calendar
    calendar=$(systemctl cat eccube-fim-check.timer 2>/dev/null | awk -F= '/^OnCalendar=/{print $2}')
    CHECK_INTERVAL="${calendar##*:0/}"
    CHECK_INTERVAL="${CHECK_INTERVAL:-15}"
}

wizard() {
    local daemon_f="$CONFIG_DIR/daemon.yaml"
    local notify_f="$CONFIG_DIR/notify.yaml"
    # Skip wizard whenever configs exist — interactive or not — unless --reconfigure
    if [ -f "$daemon_f" ] && [ -f "$notify_f" ] && [ "$RECONFIGURE" -eq 0 ]; then
        info "Existing config found — skipping wizard (use --reconfigure to change settings)"
        ECCUBE_ROOT=$(awk '/^root_path:/{print $2}' "$daemon_f")
        ECCUBE_ROOT="${ECCUBE_ROOT:-/var/www/html}"
        _read_interval_from_timer
        return
    fi
    prompt_infra
    wizard_notify      # tty guard + email/Slack prompts + writes notify.yaml
    write_daemon_yaml
    write_targets_yaml
}
# ---------------------------------------------------------------------------
# Git hardening
# ---------------------------------------------------------------------------
secure_git_dir() {
    if [ ! -d "$ECCUBE_ROOT/.git" ]; then
        warn "$ECCUBE_ROOT/.git not found"
        return
    fi
    chown -R root:root "$ECCUBE_ROOT/.git"
    chmod -R go-rwx "$ECCUBE_ROOT/.git"
    info ".git permissions set to root:root go-rwx"
    if ! id "$WEB_USER" >/dev/null 2>&1; then
        warn "Web user '$WEB_USER' not found — verify .git permissions manually"
        return
    fi
    if su -s /bin/sh "$WEB_USER" -c "ls $ECCUBE_ROOT/.git" >/dev/null 2>&1; then
        warn "$WEB_USER can access .git — check permissions"
    else
        info "$WEB_USER .git access denied"
    fi
}

install_post_merge_hook() {
    local hook_path="$ECCUBE_ROOT/.git/hooks/post-merge"
    if [ ! -d "$ECCUBE_ROOT/.git/hooks" ]; then
        warn "$ECCUBE_ROOT/.git/hooks not found — skipping post-merge hook"
        return
    fi
    cat > "$hook_path" <<EOF
#!/bin/bash
# Restore web user ownership on all working tree files after git pull,
# then re-secure .git so only root can access it.
# Generated by eccube-fim install.sh — do not edit manually.
WEB_USER="${WEB_USER}"
ECCUBE_ROOT="${ECCUBE_ROOT}"
chown -R "\$WEB_USER:\$WEB_USER" "\$ECCUBE_ROOT"
chown -R root:root "\$ECCUBE_ROOT/.git"
chmod -R go-rwx "\$ECCUBE_ROOT/.git"
EOF
    chmod 700 "$hook_path"
    chown root:root "$hook_path"
    info "post-merge hook installed: $hook_path"
}

# known: 53 lines — body is sequential warn output; no extractable logic
_warn_root_ssh() {
    local remote_url
    remote_url=$(git -c "safe.directory=$ECCUBE_ROOT" \
                     -C "$ECCUBE_ROOT" remote get-url origin 2>/dev/null) || return 0

    # HTTP(S) remotes do not need an SSH key
    if echo "$remote_url" | grep -qE '^https?://'; then
        return 0
    fi

    # Root already has a usable private key — no action needed
    if ls /root/.ssh/id_* 2>/dev/null | grep -qv '\.pub$'; then
        return 0
    fi

    local web_home
    web_home=$(getent passwd "$WEB_USER" | cut -d: -f6)

    # Scan candidate dirs: getent home first, then common httpd shared locations
    # because apache's home may be /usr/share/httpd while the key lives elsewhere
    local web_key=""
    for _dir in "${web_home}/.ssh" /usr/share/httpd/.ssh /etc/httpd/.ssh \
                /var/www/.ssh /var/lib/apache/.ssh; do
        for _k in id_ed25519 id_ecdsa id_rsa; do
            [ -f "$_dir/$_k" ] && { web_key="$_dir/$_k"; break 2; }
        done
    done

    warn "Remote is SSH but root has no private key in /root/.ssh/"
    warn "git pull as root will fail with 'Permission denied (publickey)'"
    warn "Choose one of the following options to fix this:"
    echo >&2
    warn "  Option A — reuse the existing deploy key via /root/.ssh/config:"
    warn "    mkdir -p /root/.ssh && chmod 700 /root/.ssh"
    warn "    cat >> /root/.ssh/config <<EOF"
    warn "Host *"
    if [ -n "$web_key" ]; then
        warn "    IdentityFile $web_key"
    else
        warn "    IdentityFile <path-to-${WEB_USER}-deploy-key>"
        warn "    # Locate key: sudo -u $WEB_USER ssh-add -l 2>/dev/null"
        warn "    #             or check ${web_home}/.ssh/ and /etc/httpd/.ssh/"
    fi
    warn "EOF"
    warn "    chmod 600 /root/.ssh/config"
    echo >&2
    warn "  Option B — generate a new key for root and register it:"
    warn "    ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ''"
    warn "    cat /root/.ssh/id_ed25519.pub   # add to GitHub/GitLab deploy keys"
    echo >&2
    warn "  Option C — forward your SSH agent when running git pull:"
    warn "    sudo -E git -c \"safe.directory=$ECCUBE_ROOT\" -C \"$ECCUBE_ROOT\" pull"
}

warn_uncommitted_changes() {
    if ! git -c "safe.directory=$ECCUBE_ROOT" -C "$ECCUBE_ROOT" \
            status --porcelain 2>/dev/null | grep -qE '^[MD]'; then
        return
    fi
    warn "Uncommitted changes detected in $ECCUBE_ROOT"
    git -c "safe.directory=$ECCUBE_ROOT" -C "$ECCUBE_ROOT" status --short
}

# ---------------------------------------------------------------------------
# systemd units — template substitution
# ---------------------------------------------------------------------------
install_systemd_files() {
    info "Installing systemd units (interval: ${CHECK_INTERVAL}m, root: $ECCUBE_ROOT)"
    sed \
        -e "s|%%ECCUBE_ROOT%%|${ECCUBE_ROOT}|g" \
        -e "s|%%SBIN_DIR%%|${SBIN_DIR}|g" \
        -e "s|%%RUN_DIR%%|${RUN_DIR}|g" \
        -e "s|%%CONFIG_DIR%%|${CONFIG_DIR}|g" \
        -e "s|%%STATUS_DIR%%|${STATUS_DIR}|g" \
        "$SRC_DIR/systemd/eccube-fim-check.service" \
        > /etc/systemd/system/eccube-fim-check.service
    sed "s|%%INTERVAL%%|${CHECK_INTERVAL}|g" \
        "$SRC_DIR/systemd/eccube-fim-check.timer" \
        > /etc/systemd/system/eccube-fim-check.timer
    chmod 644 /etc/systemd/system/eccube-fim-check.service \
              /etc/systemd/system/eccube-fim-check.timer
    systemctl daemon-reload
}

activate_systemd_units() {
    systemctl enable eccube-fim-check.timer
    systemctl restart eccube-fim-check.timer
}

# ---------------------------------------------------------------------------
# Force-retry mode — run migrations only; code already installed on disk
# ---------------------------------------------------------------------------
migrate_only_mode() {
    # Retry path after a failed --update: skip re-download and jump straight to migrations.
    local daemon_f="$CONFIG_DIR/daemon.yaml"
    [ -f "$daemon_f" ] || { error "No config found — run without --update for a fresh install"; exit 1; }
    info "Force-retry: running migrations only (code already installed)"
    "$SBIN_DIR/eccube-fim" _migrate --config-dir "$CONFIG_DIR" || {
        error "Migrations still failing — fix the error above, then retry."
        error "Manual path: $SBIN_DIR/eccube-fim _migrate --config-dir $CONFIG_DIR"
        exit 1
    }
    install_version_stamp
    ECCUBE_ROOT=$(awk '/^root_path:/{print $2}' "$daemon_f")
    _read_interval_from_timer
    install_systemd_files
    systemctl restart eccube-fim-check.timer
    install_post_merge_hook
    info "Force-retry complete"
}

# ---------------------------------------------------------------------------
# Update mode — refresh code + units, preserve config
# ---------------------------------------------------------------------------
update_mode() {
    local daemon_f="$CONFIG_DIR/daemon.yaml"
    [ -f "$daemon_f" ] || { error "No config found — run without --update for a fresh install"; exit 1; }
    guard_existing_malware_version
    install_common_library
    install_fim_library
    install_cli
    install_logrotate
    # run after new lib + binary are in place so new migration files are used
    "$SBIN_DIR/eccube-fim" _migrate --config-dir "$CONFIG_DIR" || {
        error "Migrations failed — upgrade aborted"
        error "To retry migrations without reinstalling: $SBIN_DIR/eccube-fim upgrade --migrate-only"
        error "To retry manually: $SBIN_DIR/eccube-fim _migrate --config-dir $CONFIG_DIR"
        exit 1
    }
    # stamp written only after migrations succeed so a failed upgrade is retryable
    install_version_stamp
    # belt-and-suspenders: LogsDirectory handles this on service start, but update_mode
    # runs before the service restarts so old installs without LogsDirectory still get the dir
    mkdir -p "$LOG_DIR" && chmod 700 "$LOG_DIR" && chown root:root "$LOG_DIR"
    mkdir -p "$STATUS_DIR" && chmod 755 "$STATUS_DIR" && chown root:root "$STATUS_DIR"
    ECCUBE_ROOT=$(awk '/^root_path:/{print $2}' "$daemon_f")
    _read_interval_from_timer
    install_systemd_files
    systemctl restart eccube-fim-check.timer
}

# ---------------------------------------------------------------------------
# Post-install verification offer
# ---------------------------------------------------------------------------
# known: 43 lines — sequential prompt flow; splitting would require passing $run_validate as state
post_install_checks() {
    echo
    local fim_cmd="$SBIN_DIR/eccube-fim"

    if [ "$NONINTERACTIVE" -eq 1 ]; then
        info "Next: $fim_cmd config validate"
        if [ "${EMAIL_ENABLED:-true}" = "true" ]; then
            info "Next: $fim_cmd test mail"
        fi
        info "Finished."
        return
    fi

    # empty Enter → variable is "", which is != "n", so default is Y
    local run_validate

    if [ ! -x "$fim_cmd" ]; then
        warn "$fim_cmd not found or not executable — run config validate/test mail manually after fixing install"
        info "Finished."
        return
    fi

    read -rp "Run '$fim_cmd config validate' now? [Y/n]: " run_validate </dev/tty
    if [ "${run_validate,,}" != "n" ]; then
        echo
        if "$fim_cmd" config validate </dev/null; then
            if [ "${EMAIL_ENABLED:-true}" = "true" ]; then
                local run_testmail
                read -rp "Send test email via '$fim_cmd test mail' now? [Y/n]: " run_testmail </dev/tty
                if [ "${run_testmail,,}" != "n" ]; then
                    echo
                    "$fim_cmd" test mail </dev/null || warn "test mail failed — check notify.yaml and SMTP credentials"
                fi
            fi
        else
            warn "validate failed — fix config before running test mail"
        fi
    fi

    echo
    info "Finished."
    return 0
}

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
# known: 45 lines — orchestration function; length reflects install steps, not complexity
main() {
    parse_args "$@"
    require_root
    configure_os

    if [ "$UPDATE" -eq 1 ] && [ "$FORCE" -eq 1 ]; then
        fetch_source
        migrate_only_mode
        info "Update complete"
        return
    fi

    if [ "$UPDATE" -eq 1 ]; then
        fetch_source
        info "EC-CUBE FIM installer (version: ${VERSION}, OS: ${OS_ID})"
        install_packages
        update_mode
        install_post_merge_hook
        info "Update complete"
        post_install_checks
        return
    fi

    fetch_source
    info "EC-CUBE FIM installer (version: ${VERSION}, OS: ${OS_ID})"
    install_packages
    create_directories
    setup_tmpfiles
    guard_existing_malware_version
    install_common_library
    install_fim_library
    install_version_stamp
    install_cli
    install_logrotate
    wizard
    secure_git_dir
    install_post_merge_hook
    _warn_root_ssh
    warn_uncommitted_changes
    install_systemd_files
    activate_systemd_units
    info "Install complete"
    post_install_checks
    return 0
}

main "$@"
exit $?
